# Generated by Django 3.1.4 on 2020-12-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_app', '0002_auto_20201225_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='imageurl',
        ),
    ]
