# Generated by Django 3.1.4 on 2020-12-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_app', '0003_auto_20201226_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='imageurl',
            new_name='image_url',
        ),
    ]
