# Generated by Django 3.1.4 on 2020-12-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_app', '0005_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='name',
            field=models.CharField(default='New Image', max_length=50),
        ),
    ]
